#### Ques 1. Create a vector with values ranging from 10 to 49 


In [6]:
import numpy as np
v = np.arange(10,50)
print("vector:")
print(v)

vector:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### Ques 2.  Reverse a vector (first element becomes last)


In [8]:
import numpy as np
import numpy as np
x = np.arange(10, 50)
print("vector:")
print(x)
print("Reverse vector:")
x = x[::-1]
print(x)

vector:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
Reverse vector:
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


####  Ques 3.Create a 3x3 identity matrix

In [9]:
import numpy as np
array_2D=np.identity(3)
print('3x3 matrix:')
print(array_2D)

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Ques 4. Create a 10x10 array with random values and find the minimum and maximum values

In [10]:
import numpy as np
x = np.random.random((5,5))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.09130966 0.31438858 0.29603108 0.33600018 0.4638168 ]
 [0.18946842 0.8200343  0.09104707 0.42655906 0.35471112]
 [0.4038016  0.5244888  0.3468072  0.6534476  0.82229643]
 [0.53456645 0.91760343 0.06393033 0.57507368 0.63666504]
 [0.50229546 0.46064378 0.51900497 0.36325307 0.73366113]]
Minimum and Maximum Values:
0.06393032857962522 0.9176034301826095


#### Ques 5.What is the result of the following expression?
#### 0 * np.nan
#### np.nan == np.nan
#### np.inf > np.nan
#### np.nan - np.nan
#### np.nan in set([np.nan])
#### 0.3 == 3 * 0.1


In [1]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

NameError: name 'np' is not defined

In [4]:
import numpy as np
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

#### Ques 6.How to sum a small array faster than np.sum? 

In [1]:
import numpy as np
a = np.arange(10,50)
np.add.reduce(a)

1180

#### Ques 7.How to find the closest value (to a given scalar) in a vector?

In [3]:
import numpy as np
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

71
